name: storybook_test

on: [push]

jobs:
  storybook_test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: StorybookTest
        uses: ./.github/actions/storybook_test